import React from 'react'
import { useNavigate } from 'react-router-dom';
import Button from 'react-bootstrap/Button';
import Logo from '../../assets/images/logo/logo_dark.png'
import './Privacy.css'
function Privacy() {
  const navigate = useNavigate();
  return (
    <div className='terms-main-container'>
    <div className='terms-main'>
        <div className='terms-nav'>
            <div className='terms-logo'>
                <img src={Logo} alt="" />
            </div>
            <div className='term-home'>
            <a href="/" className="home-link">HOME</a>
            </div>
            <div className='terms-button'>
                <div className='term-login'>
                <Button variant="outline-primary" onClick={() => navigate('/login')} >Log In</Button>{' '}
                </div>
                <div className='term-signup'>
                <Button variant="primary" onClick={() => navigate('/')}> Sign Up </Button>
                </div>
            </div>


        </div>
        <div className='term-header'>
        
            <div className='term-links'>
                <a href="/terms" className="other-link">Terms and Conditions</a>
                <a href="/" className="term-link">Privacy Policy</a>
                <a href="/user" className="other-link">User Agreement</a>
                <a href="/responsible" className="other-link">responsible gaming</a>
               

            </div>
            <div className='terms-condition'>
                <div className='terms-text'>
                <p className='terms-contents'>
                1. Information Collection: We collect various types of user information to provide access to Electro5050, improve user experience, and communicate important updates. This includes but is not limited to email addresses, usernames, and game preferences.<br></br><br></br>
                2. Use of Information: We use collected information to personalize your experience on Electro5050, optimize platform functionality, and communicate game-related updates and promotions.
                3. Information Sharing: We do not share your personal information with third parties for marketing purposes. However, we may share aggregated and anonymized data with advertisers, sponsors, and partners for analytical and promotional purposes.<br></br><br></br>
                4. Data Security: We take reasonable measures to protect your data from unauthorized access, alteration, or disclosure. While we strive to maintain the security of your information, no online transmission or storage system is completely secure.<br></br><br></br>
                5. Cookies and Tracking: Electro5050 may use cookies, web beacons, and similar technologies to enhance user experience, monitor traffic patterns, and gather information about your interactions with the platform.<br></br><br></br>
                i. What are cookies? A cookie is a piece of information in the form of a very small text file that is placed on an internet user's computer. It is generated by a web page server (which is basically the computer that operates the website) and can be used by that server
                whenever the user visits the site. A cookie can be thought of as an internet user's identification card, which tells a website when the user has returned. Cookies can't harm your computer and we don't store any personally identifiable information about you on any of our cookies.<br></br><br></br>
                ii. Why do we use cookies? Electro5050 uses two types of cookies: cookies set by us and cookies set by third parties (i.e. other websites or services). Electro5050 cookies enable us to keep you signed into your account throughout your visit and to tailor the information displayed on the site to your preferences.<br></br><br></br>
                iii. How can I manage my cookies on electro5050? If you wish to stop accepting cookies, you can do so through the Privacy Settings option in your browser.<br></br><br></br>
                iv. Server Protection Policy<br></br>
                All servers have full encryption;<br></br>
                All backups have encryption;<br></br>
                Firewalls, VPN Access;<br></br>
                Access to servers allowed only over VPN;<br></br>
                All http/s services work over Cloudflare;<br></br>
                Connections to nodes over VPN;<br></br>
                SSH port forwarding tunnels;<br></br>
                Services allowed only over VPN;<br></br>
                Server have firewall and allowed only SSH port;<br></br>
                Alerts on critical services.<br></br>
                Data Breach Notification<br></br>
                When Electro5050 will be made aware of personal data breaches we will notify<br></br>
                relevant users in accordance with GDPR timeframes.<br></br>
                v. Data International Transfer We only disclose personal data to third parties where it is necessary to provide the high-quality service or in order to respond lawful requests from authorities.<br></br><br></br>
                vi. Personal Data Protection Policy Electro5050’s mission is to keep your Data safe and for this matter we protect your data in various ways. We provide our customers with high security standards, such as encryption of data in motion over public networks, encryption of data in database, auditing standards, Distributed Denial of Service mitigations, and a Live Chat available on-site.<br></br><br></br>
                6. Third-Party Links: Electro5050 may contain links to third-party websites or applications. We are not responsible for the content, practices, or privacy policies of such third parties.<br></br><br></br>
                7. Your Choices: You have the right to access, correct, and delete your personal information on Electro5050. You can also choose to opt out of receiving certain communications.<br></br><br></br>
                8. Changes to Policy: We reserve the right to update our Privacy Policy as necessary. Continued use of Electro5050 after changes implies your acceptance of the updated policy. Please review the policy periodically.<br></br><br></br>
                9. Privacy Violation: Any unauthorized disclosure, sharing, or misuse of user information, as outlined in our Privacy Policy, is considered a violation of our terms and conditions.<br></br><br></br>
                10. Technical Issues: Although we try to do our best, problems could occur now and then. Our team will do everything we could to solve your problems as soon as possible.<br></br><br></br>
                To assist you quicker, if an error occurs, please provide the following information and mail to us or use Live support in the game.<br></br><br></br>
                Username<br></br>
                Date and time of the problem<br></br>
                Game ID Screenshot of the error, if possible<br></br><br></br>
                We really appreciate your help and the error report you provided because your information report could<br></br>
                help us improve.<br></br><br></br>
                11. Information From Third Party Social Media Service:<br></br><br></br>
                Electro5050 allows You to create an account and log in to use the Service through the following Third- party Social Media Services:<br></br><br></br>
                • Google<br></br>
                • Facebook<br></br>
                • Telegram<br></br>
                • Instagram<br></br><br></br>
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, we may collect Personal data that is already associated with Your Third-Party Social Media Service's account, such as Your name, your email address, your activities or Your contact list associated with that account. You may also have the option of sharing additional information with the Electro5050 through Your Third- Party Social Media Service's account. If You choose to provide such information and Personal Data, during registration or otherwise, you are giving Electro5050 permission to use, share, and store it in a manner consistent with this Privacy Policy.<br></br><br></br>
                12. Delete Personal Data:<br></br>
                You can request to have your personal data deleted if Electro5050 no longer have a legal reason to continue to process or store it. Please note that this right is not guaranteed - in the sense that Electro5050 do not have the ability to comply with your request if it is subject to a legal obligation to store your data. You can request the deletion of your personal data by sending an email to [our support email here]<br></br><br></br>
                </p>
                   
                </div>
                
            </div>
        </div>
        
       


    </div>
  
</div>
  )
}

export default Privacy
